DeaAnalytics:
  outputs:
    dev:
      dataset: DeaAnalytics
      project: DeaAnalyticsGoogleId
      location: us-east4
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      priority: interactive
      threads: 1
      type: bigquery
  target: dev
